// Legal content copied from the live shynlicleaningservice.com legal pages on 2026-05-10.
export const legalPages = [
  {
    "slug": "terms",
    "path": "/terms",
    "title": "Terms of Service",
    "description": "SHYNLI LLC Terms of Service for cleaning services, booking, scope, payment, cancellations, liability, and dispute terms.",
    "sourceUrl": "https://shynlicleaningservice.com/terms-of-service",
    "lines": [
      "TERMS OF SERVICE",
      "SHYNLI LLC (Illinois)",
      "Last Updated: 02.16.2026",
      "Time Zone: America/Chicago (Central Time)",
      "These Terms of Service (\"Terms\") are a legally binding agreement between you (\"Client,\" \"you\") and SHYNLI LLC, an Illinois limited liability company (\"Company,\" \"we,\" \"us,\" \"our\").",
      "By requesting a quote, booking, scheduling, approving an estimate, clicking \"Book/Confirm,\" paying an invoice, or otherwise using our cleaning services, website, or communications (calls, SMS/text messages, email) (collectively, the \"Services\"), you agree to these Terms.",
      "IMPORTANT NOTICE (KEY TERMS):",
      "- CANCELLATION / NO-SHOW FEES MAY APPLY (SECTION 16).",
      "- MISSING-ITEM LIABILITY IS CAPPED (SECTION 12.6).",
      "- LIMITATION OF LIABILITY APPLIES (SECTION 24).",
      "- NON-SOLICITATION OF OUR STAFF (LIQUIDATED DAMAGES) (SECTION 19).",
      "- ARBITRATION / JURY TRIAL WAIVER / CLASS ACTION WAIVER (SECTION 26).",
      "1. ELIGIBILITY, AUTHORITY, AND ACCEPTANCE",
      "By using the Services, you represent and warrant that:",
      "(a) you are at least 18 years old;",
      "(b) you have the legal capacity to enter into a contract;",
      "(c) if acting for a business/entity, you have authority to bind that entity; and",
      "(d) you will comply with applicable laws and building rules.",
      "Electronic Acceptance. Booking online, approving an estimate, clicking \"Book/Confirm,\" or paying an invoice constitutes electronic acceptance and a binding agreement.",
      "2. SERVICES, SCOPE OF WORK, AND DEFINITIONS",
      "2.1 Scope",
      "Company provides residential and/or commercial cleaning services only as described and confirmed at booking (package/service level, checklist, order confirmation, proposal, estimate, or invoice) (\"Scope\").",
      "Checklist Incorporated by Reference (Controls). The checklist and service level selected at booking are incorporated into these Terms by reference and control over general descriptions. Deep cleaning, move-in/move-out, and short-term rental turnovers (if offered) have defined inclusions/exclusions as presented at booking and/or on the checklist.",
      "2.2 Out-of-Scope Tasks / Add-Ons",
      "Any additional tasks require prior approval and may require additional time and additional charges.",
      "2.3 Not Restoration or Specialty Remediation",
      "Unless expressly agreed in writing, Company does not provide restoration, hazardous cleanup, biohazard remediation, hoarding cleanup, sewage backup cleanup, mold remediation, asbestos/lead abatement, pest extermination, or any service requiring special licensing or PPE beyond standard cleaning.",
      "2.4 Short-Term Rentals (Airbnb/VRBO) - Scope Limits",
      "For short-term rentals, \"turnover\" tasks (including laundry/linen changes, restocking supplies, dishwashing, exterior areas, patios/garages, or guest-specific setup) are not included unless expressly listed in the Scope/checklist.",
      "2.5 Trash Removal / No Hauling",
      "Trash removal is limited to standard interior waste bins and bagged trash placed in designated areas, unless otherwise stated in the Scope. No hauling, bulk-item removal, construction debris removal, or large-item disposal is included unless quoted and agreed in writing.",
      "3. CLIENT INFORMATION: ACCURACY AND DISCLOSURES",
      "Client must provide true, complete, and current information, including:",
      "(a) property type, approximate size, rooms/bathrooms;",
      "(b) actual condition/soil level (buildup, grease, heavy grime, post-renovation, move-in/move-out, etc.);",
      "(c) fragile or specialty surfaces/materials;",
      "(d) pets and behavioral considerations;",
      "(e) special requests and restrictions; and",
      "(f) access/parking constraints and building requirements.",
      "If there is a material mismatch between provided information and actual conditions, Company may (at its discretion) adjust Scope, extend time, modify pricing, offer a different service level, reschedule, or refuse/stop service.",
      "4. \"STANDARD CONDITION\" REQUIREMENT AND EXCLUDED CONDITIONS",
      "Client represents that the premises are in \"Standard Condition,\" meaning:",
      "(a) no biohazards (blood, feces, urine, vomit, needles/sharps, etc.);",
      "(b) no active infestations (insects/rodents);",
      "(c) no hazardous substances or unsafe air conditions;",
      "(d) no active construction/renovation work or contractors on-site interfering with cleaning;",
      "(e) no excessive clutter that prevents safe cleaning; and",
      "(f) no conditions creating risk of injury/harm to staff.",
      "Definition - Excessive Clutter. \"Excessive clutter\" means surfaces/floors are not reasonably accessible for cleaning without moving large quantities of personal items, trash, or hazardous materials, or where pathways/working areas are obstructed.",
      "If the premises are not in Standard Condition, Company may refuse or stop service. Cancellation/no-show rules may apply (Section 16).",
      "5. ACCESS, SITE REQUIREMENTS, AND CLIENT RESPONSIBILITIES",
      "Client must provide:",
      "(a) access to the premises at the scheduled time;",
      "(b) working lighting, electricity, and running water;",
      "(c) entry/parking instructions, building rules, door codes, elevator access, lockbox instructions, etc.; and",
      "(d) a safe work environment.",
      "Fragile Items / Clearing Areas. Client must clear fragile items, valuables, and loose personal property from active cleaning areas. Company is not responsible for loss/breakage of items left unsecured in active work areas except to the extent caused by Company's negligence.",
      "Short-Term Rentals. Client is responsible for ensuring the property will be vacant/available during the scheduled window and that access will not be blocked by guests, timers, or building restrictions.",
      "No Access / Unreachable. If our team arrives and access is not provided, instructions are incorrect, the site is closed, building/security denies entry, or Client is unreachable, the appointment may be treated as a no-show under Section 16.",
      "Waiting Time. If our team cannot enter within 15 minutes of arrival due to access issues, the appointment may be treated as a no-show under Section 16. If Client requests the team to remain beyond 15 minutes, waiting time may be billed at $45/hour, prorated, subject to availability.",
      "5.1 Keys, Lockboxes, Smart Locks, and Locksmiths",
      "If Client provides keys/lockbox access, Client is responsible for providing working access instructions. If access fails and service cannot proceed, it may be treated as no access/no-show (Section 16). Unless required by law, Company is not responsible for locksmith costs resulting from incorrect codes/lockouts caused by Client's access instructions or building systems.",
      "5.2 Utilities / Equipment Failures",
      "Company is not responsible for delays, incomplete work, or reduced results due to loss of water, power, heat/AC, elevator outages, building restrictions, or broken/unsafe equipment provided by Client. If utilities or access conditions prevent safe or reasonable performance, Company may reschedule or stop service, and Section 16 may apply where appropriate.",
      "5.3 Arrival Times / Windows (Reasonable Credit Standard)",
      "Appointment times are estimated service windows. Delays may occur due to traffic, weather, building access, or conditions at prior jobs.",
      "If we arrive more than 60 minutes late for reasons within Company's reasonable control and cannot complete the booked Scope, we will reschedule at no charge or issue a proportional credit for the unperformed portion (Company's choice), unless a different remedy is required by law.",
      "To the maximum extent permitted by law, Company is not liable for delay-related consequential losses (including guest refunds, lost rental income, or business interruption).",
      "6. SAFETY, ZERO-TOLERANCE CONDUCT POLICY, AND RIGHT TO REFUSE/TERMINATE",
      "Company may refuse, suspend, or immediately terminate Services (including after commencement) if:",
      "(a) conditions are unsafe or become unsafe;",
      "(b) Client/occupants/site staff/third parties behave aggressively, threateningly, harassingly, degradingly, discriminatory, or otherwise inappropriately;",
      "(c) children are present without a responsible adult, or children's presence prevents safe performance;",
      "(d) pets, hazards, bio-risks, active work, or other conditions create safety concerns; or",
      "(e) weapons are displayed, illegal substances are present in plain view, or the environment appears hostile or unsafe in Company's reasonable judgment.",
      "Fees / No Refunds for Safety Termination. To the extent permitted by law, if Services are terminated for safety reasons, Company may retain amounts reasonably related to reserved labor time, dispatch/travel, and costs incurred, and may invoice for work performed prior to termination. Nothing in these Terms limits refunds required by applicable law. Company may restrict future service.",
      "7. PETS",
      "Pets must be secured/isolated and must not interfere with the team. Client must disclose aggressive or unpredictable pets. Company is not responsible for pet escapes if Client fails to secure doors/enclosures/separate zones. Pet-related contamination and strong biological odors are not included in standard cleaning and require separate approval.",
      "8. RECORDING, CAMERAS, AND PRIVACY ON SITE",
      "Client must disclose in advance any cameras or recording devices on the premises.",
      "Audio-Enabled Cameras / Devices. Any camera or device that captures audio (including \"video cameras\" with audio enabled) is considered an audio recording device.",
      "Audio Disabled by Default. Client must disable audio recording on any device during service unless Company provides prior written consent and all parties provide consent as required by law.",
      "No Undisclosed Audio Recording. Company does not consent to any undisclosed audio recording of private conversations.",
      "Company Call Recording (If Applicable). Where permitted by law, Company may record inbound and outbound calls for quality assurance, training, and dispute resolution. By communicating with Company by phone after receiving a recording notice (including an automated notice at call start where used), you consent to recording to the extent permitted by applicable law.",
      "Video-only security cameras are permitted if disclosed and positioned in common areas; no cameras in bathrooms/bedrooms or other private areas. Violations may result in immediate termination (Section 6) and fees may apply (Section 16).",
      "9. PHOTOS AND QUALITY CONTROL",
      "Company may take \"before/after\" photos solely for internal quality control, training, and dispute review. Company will use reasonable efforts to avoid capturing people, personal documents, or sensitive items.",
      "Permitted Disclosure. We may share such photos with our insurers, legal counsel, and/or dispute-resolution providers as reasonably necessary to investigate, defend, or resolve a claim or dispute.",
      "Retention. Photos are typically retained for up to 90 days, unless longer retention is reasonably needed for a dispute.",
      "Opt-Out. Client may opt out by notifying Company before service begins (phone/SMS/email/message).",
      "10. NO GUARANTEE OF \"PERFECT RESULTS\"",
      "Results depend on condition, wear, materials, and prior maintenance. Company does not guarantee removal of old/stubborn stains/odors or restoration of worn, fragile, defective, or improperly installed surfaces.",
      "11. QUALITY GUARANTEE / RE-CLEAN (PRIMARY REMEDY)",
      "If Client is dissatisfied, Client may request correction/re-clean by:",
      "(a) notifying Company within 48 hours after completion;",
      "(b) providing photos and a description of the affected areas; and",
      "(c) providing reasonable access for inspection and re-clean within a reasonable timeframe, subject to availability.",
      "Company may choose a reasonable resolution: re-clean, spot correction, or credit/discount. Re-clean is the primary remedy for quality issues.",
      "If Client refuses reasonable access or a reasonable re-clean opportunity, Company may deny further courtesy remedies to the extent permitted by law.",
      "Nothing in this Section limits non-waivable rights under applicable law.",
      "12. DAMAGES, MISSING ITEMS, AND CLAIMS PROCESS",
      "12.1 Reporting Timing (Damage / Missing Items)",
      "Client must report claims promptly, and in any event within 7 days after the appointment.",
      "Latent Damage. If damage could not reasonably be discovered within 7 days, Client must report it within 30 days of discovery, provided that (unless required by law) the report is made no later than 60 days after the appointment and is supported by reasonable evidence.",
      "12.2 Pre-Existing / Wear-and-Tear Exclusions",
      "Company is not responsible for pre-existing damage, normal wear and tear, fragile/aged/weakened components, material defects, improper installation, or prior repairs.",
      "12.3 Valuables and Unsecured Items",
      "Client is responsible for securing cash, jewelry, collectibles, small electronics, prescription items, and other high-value or sentimental property. Company is not liable for loss or damage to such items unless disclosed in writing before service and Company expressly agreed in writing to handle them.",
      "12.4 Inspection First / No Unauthorized Repairs (Commercially Reasonable)",
      "Client must allow Company a commercially reasonable opportunity to inspect and, at Company's option, repair/replace via commercially reasonable vendors, without unreasonable delay. Client shall not authorize non-emergency repairs or replacements without Company's prior written consent, or Company may deny reimbursement.",
      "12.5 Missing Items",
      "Missing-item claims must include a specific description and last-known location. Company is not responsible for items discarded or relocated due to clutter, trash removal instructions, or actions of third parties.",
      "12.6 MISSING ITEMS CAP (CONSPICUOUS)",
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR A VALIDATED MISSING-ITEM CLAIM WILL NOT EXCEED THE LESSER OF (I) $250 PER APPOINTMENT OR (II) THE AMOUNT PAID FOR THAT APPOINTMENT, UNLESS THE ITEM WAS DISCLOSED IN WRITING BEFORE SERVICE AND WE EXPRESSLY ACCEPTED RESPONSIBILITY IN WRITING.",
      "THIS CAP DOES NOT APPLY TO OUR GROSS NEGLIGENCE OR WILLFUL MISCONDUCT WHERE SUCH LIMITATION IS NOT PERMITTED BY LAW.",
      "12.7 Time Limit to Bring Claims (Residential vs Commercial)",
      "Residential Clients. Any claim or action arising out of or related to the Services must be brought within two (2) years after the service date giving rise to the claim, to the extent permitted by applicable law.",
      "Commercial/Business Clients. Any claim or action arising out of or related to the Services must be brought within one (1) year after the service date giving rise to the claim, to the extent permitted by applicable law.",
      "13. HEAVY LIFTING, FURNITURE MOVING, AND LADDER POLICY",
      "Unless expressly agreed in writing, Company does not move heavy furniture/appliances or perform tasks requiring specialty equipment or unsafe ladder work.",
      "14. SUPPLIES, CLIENT-PROVIDED PRODUCTS, AND SENSITIVITIES",
      "Company may use its standard supplies and products. If Client requests the use of Client-provided products/equipment, Client is responsible for suitability, instructions, allergies/sensitivities disclosures, and any resulting damage or ineffective results.",
      "15. ADDITIONAL TIME AND ADD-ON WORK",
      "If additional time is needed due to property condition, inaccurate information, or new requests, Company may offer extended time:",
      "Rate: $45/hour (billed in 15-minute increments);",
      "Requires Client consent (including by SMS/text);",
      "Subject to availability.",
      "If Client declines additional time or a scope upgrade, Company will perform Services within the booked time and confirmed Scope priorities to the extent reasonably possible. Any remaining tasks may require rescheduling, a different service level, or additional time at the stated rate.",
      "16. CANCELLATIONS, RESCHEDULES, AND NO-SHOWS (LIQUIDATED DAMAGES)",
      "All time references are in America/Chicago (Central Time).",
      "Fee Basis / Cap (Non-Resellable Time). Client agrees that cancellation/no-show fees are liquidated damages intended to cover booked labor time reserved for the Client plus dispatch/processing costs. Such fees will not exceed the value of booked service time that cannot reasonably be resold (and will never exceed the booked price), and are intended to compensate-not punish.",
      "16.1 Cancellation / Reschedule Fees",
      "If Client cancels or reschedules:",
      "(a) More than 48 hours before the appointment: $0",
      "(b) 24-48 hours before the appointment: $50 flat fee",
      "(c) 12-24 hours before the appointment: 50% of the booked price",
      "(d) Less than 12 hours before the appointment OR same-day cancellation: 100% of the booked price",
      "16.2 No-Show / No Access",
      "If the team arrives but access is not provided (locked door, missing/incorrect code/key, building/security denies entry, Client does not respond, incorrect instructions, or no confirmed access), the appointment is a no-show and Company may charge 100% of the booked price, including reserved team time and dispatch/travel-related costs.",
      "16.3 Mandatory Rebook Reduction (Mitigation)",
      "If we successfully rebook the cancelled or rescheduled time slot, we will reduce your cancellation fee by the amount of labor revenue recovered from the replacement booking (excluding non-refundable dispatch/processing costs already incurred), up to the fee charged.",
      "17. PRICING, DISCOUNTS, AND CHANGES",
      "Company may change pricing, packages, and discounts. Confirmed pricing may be adjusted if Client provided inaccurate information, Scope changes, and/or non-standard conditions are discovered. Any change will be communicated before work continues and may require Client approval (including by text).",
      "17.1 Pricing Errors",
      "Company may correct obvious pricing, typographical, or clerical errors before Services are performed. If corrected, Client may cancel and receive a full refund of any prepayment made for that appointment.",
      "18. PAYMENTS, PREPAYMENTS/DEPOSITS, AND UNPAID BALANCES",
      "18.1 Payment Timing",
      "Unless otherwise agreed in writing, payment is due immediately upon completion of Services and/or upon issuance of the final invoice, whichever occurs first.",
      "18.2 Approved Payment Methods",
      "Client must pay using a payment method accepted by Company.",
      "18.3 Card to Reserve Time",
      "Company may require a valid payment method to reserve an appointment time slot. Client authorizes Company to charge applicable cancellation/no-show fees under Section 16 if triggered.",
      "18.4 Prepayments / Deposits; Refund Method",
      "If a prepayment/deposit is collected, it is applied to the invoice for the appointment.",
      "Refunds (if any) will be issued to the same payment method originally used (or, if not feasible, an equivalent method), typically within 5-7 business days, subject to bank/processor timelines, and in any event within 10 business days where required by applicable law.",
      "18.5 Nonpayment",
      "If payment is not received within 24 hours after completion, Company may suspend future services and pursue lawful collection, including recovery of reasonable collection costs as permitted by law.",
      "18.6 Chargeback Process",
      "Before initiating a chargeback, Client agrees to notify Company in writing and allow 10 business days for good-faith resolution. This does not waive any rights Client may have under applicable law.",
      "19. NON-SOLICITATION OF COMPANY STAFF / CONTRACTORS (RESIDENTIAL-FRIENDLY)",
      "Client agrees not to knowingly solicit, hire, or engage directly (for paid cleaning services) any Company employee or contractor who performed Services for Client on behalf of Company within the prior 12 months (\"Restricted Personnel\").",
      "\"Incident\" means one (1) engagement or attempted engagement for paid cleaning services outside Company, whether for one cleaning visit or an ongoing arrangement.",
      "Exclusions. This Section does not apply where (i) the Restricted Personnel initiated contact and Client did not knowingly engage them for paid services, or (ii) Client can reasonably document that the person was not Company's personnel at the time of engagement.",
      "Cure / Warning (Residential Only). For Residential Clients, Company may provide a one-time written warning for a first suspected violation if no paid engagement has occurred and Client promptly confirms in writing they will not proceed. This does not apply to completed paid engagements.",
      "Remedies. Company may seek injunctive relief and actual damages including documented recruiting, screening/background checks, onboarding, training, scheduling disruption, and replacement costs.",
      "LIQUIDATED DAMAGES (CONSPICUOUS). Client acknowledges that knowingly engaging Restricted Personnel for paid cleaning services outside Company causes harm difficult to quantify at the time of contracting. Therefore, Client agrees to pay $750 in liquidated damages per Incident, as a reasonable pre-estimate of Company's replacement and disruption costs and not a penalty, in addition to any proven additional damages and injunctive relief to the extent permitted by law.",
      "20. CONSENT & COMPLIANCE - COMMUNICATIONS (SMS/CALLS/EMAIL)",
      "Consent & Compliance. We will send transactional/service messages only as reasonably necessary to provide and manage your booking (e.g., confirmations, access questions, schedule changes, invoices). We will not send marketing texts/calls without prior express written consent where required. We comply with applicable federal and Illinois law governing autodialed/prerecorded communications, including time-of-day restrictions and opt-out requirements. You may opt out of marketing at any time by replying STOP; for help reply HELP. Message frequency varies. Standard message/data rates may apply. We maintain records of consent and opt-out requests as required by law.",
      "Quiet Hours (Illinois Autodialed Calls). We will not place autodialed calls to Illinois numbers between 9:00 p.m. and 9:00 a.m. Central Time.",
      "21. FORCE MAJEURE",
      "Company is not liable for delays/rescheduling/inability to perform due to events beyond Company's reasonable control (severe weather, road conditions, power/water outages, building access restrictions, emergencies, illness, labor disruptions, governmental actions). Company may reschedule without penalty and will refund prepaid amounts for services not performed.",
      "22. PRIVACY",
      "Personal data is handled in accordance with our Privacy Policy available at: [LINK]. By using the Services, Client agrees to that policy.",
      "Security / Breach Notice. We implement reasonable safeguards and will provide breach notifications as required by applicable Illinois law.",
      "23. DISCLAIMERS",
      "To the maximum extent permitted by law, Services are provided \"AS IS\" and \"AS AVAILABLE.\"",
      "24. LIMITATION OF LIABILITY (CONSPICUOUS)",
      "TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY IS NOT LIABLE FOR INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES (INCLUDING LOST PROFITS, LOST RENTAL INCOME, AIRBNB/GUEST REFUNDS, OR BUSINESS INTERRUPTION).",
      "CAP. TO THE MAXIMUM EXTENT PERMITTED BY LAW, COMPANY'S TOTAL LIABILITY FOR ANY CLAIM WILL NOT EXCEED THE AMOUNT PAID BY CLIENT FOR THE SPECIFIC SERVICE GIVING RISE TO THE DISPUTE, UNLESS OTHERWISE REQUIRED BY LAW.",
      "CARVE-OUTS / NON-WAIVABLE RIGHTS. This limitation does not apply to liability for bodily injury or property damage caused by Company's gross negligence or willful misconduct, or any liability that cannot be limited under applicable law.",
      "Duty to Mitigate. Client agrees to take reasonable steps to mitigate damages and not to increase losses through delay, denial of access, unauthorized repairs, or other avoidable conduct.",
      "25. INDEMNIFICATION",
      "Client agrees to indemnify, defend, and hold Company harmless from claims, losses, and expenses to the extent caused by Client's breach, unsafe conditions, actions of Client/guests/third parties, or inaccurate/incomplete information, except to the extent caused by Company's negligence or willful misconduct.",
      "26. DISPUTE RESOLUTION: NOTICE, AAA ARBITRATION, CLASS ACTION WAIVER",
      "IMPORTANT:",
      "YOU UNDERSTAND THAT ARBITRATION MEANS YOU ARE WAIVING THE RIGHT TO A JURY TRIAL AND TO BRING OR PARTICIPATE IN A CLASS ACTION.",
      "26.1 Notice of Dispute (Informal Resolution)",
      "Before arbitration or court, a party must send the other party a written Notice of Dispute describing the issue and relief sought. The parties will attempt good-faith resolution for 30 days.",
      "Notices of Dispute must be sent to: info@shynli.com AND to the mailing address in Section 34 (Legal Notices), unless Company provides an updated address in writing.",
      "26.2 Small Claims Court",
      "Either party may bring an individual action in small claims court if the dispute qualifies.",
      "26.3 Individual Arbitration (AAA) / Fallback",
      "If unresolved and not in small claims court, disputes shall be resolved by binding individual arbitration governed by the FAA and administered by the American Arbitration Association (\"AAA\") under the then-current AAA Consumer Arbitration Rules.",
      "Company will take commercially reasonable steps to maintain eligibility for AAA consumer administration, including registration of the consumer arbitration clause where required and timely payment of applicable AAA fees.",
      "AAA Unavailable / Fallback. If AAA is unavailable or declines to administer the arbitration, the parties will mutually select a comparable arbitration provider that applies consumer due-process standards. If the parties cannot agree within 30 days, the dispute will proceed in court under Section 27.",
      "26.4 Location / Locale",
      "The arbitration locale will be the county where the Services were performed or Client's county of residence, unless the parties agree to a different locale in writing. Remote hearings (video/phone/written submissions) may be used as permitted by the rules.",
      "26.5 Fees and Costs",
      "Fees follow the AAA consumer fee schedule. Company pays business-side fees and deposits required by AAA; Client pays only amounts allocated to consumers by AAA, unless otherwise required by law. Each party bears its own attorneys' fees unless awarded by the arbitrator under applicable law.",
      "26.6 Class Action Waiver",
      "All disputes must be brought only on an individual basis. No class, collective, consolidated, or representative actions to the fullest extent permitted by law.",
      "26.7 Opt-Out of Arbitration",
      "Client may opt out within 60 days of the first booking by sending notice to info@shynli.com and/or by mail to: SHYNLI LLC, Attn: Arbitration Opt-Out, P.O. Box 2492",
      "Naperville IL 60566. The notice must include Client's name, address, email/phone, first booking date, and: \"I opt out of arbitration.\"",
      "26.8 Arbitration Severability",
      "If the Class Action Waiver is found unenforceable, the remainder of this Section remains in effect and any class claims shall proceed in court only to the minimum extent required by law.",
      "27. GOVERNING LAW AND VENUE",
      "Illinois law governs. If arbitration does not apply, disputes shall be heard in courts located in DuPage County, Illinois, or the county where the Services were performed, to the fullest extent permitted by law.",
      "28. ATTORNEYS' FEES AND COSTS",
      "Attorneys' fees and costs may be awarded only where permitted by applicable law or by the arbitrator/court. In actions to collect unpaid balances or enforce Section 19, the prevailing Company may seek reasonable attorneys' fees/costs to the extent permitted by law.",
      "29. CHANGES TO THESE TERMS",
      "Updates apply only to bookings made after the \"Last Updated\" date unless we provide notice and you affirmatively accept changes. For already-confirmed appointments, the Terms in effect at booking control.",
      "30. SEVERABILITY",
      "If any provision is unenforceable, the remainder remains in effect.",
      "31. ENTIRE AGREEMENT",
      "These Terms and any written addenda constitute the entire agreement.",
      "32. NO THIRD-PARTY BENEFICIARIES",
      "No third-party beneficiary rights are created.",
      "33. INDEPENDENT CONTRACTORS",
      "Company may use employees and/or independent contractors.",
      "34. NOTICES AND CONTACT",
      "General Notices. Email notices are effective when sent and not returned as undeliverable.",
      "Legal Notices (Mail). Any legal notice (including Notices of Dispute) must also be sent by mail to the address below, unless Company provides a different address in writing.",
      "Email: info@shynli.com",
      "Phone: +1(630)812-7077",
      "Website: https://shynlicleaningservice.com",
      "Mailing Address for Legal Notices (including arbitration opt-out): P.O. Box 2492",
      "Naperville IL 60566",
      "35. HOME SOLICITATION CANCELLATION (IF APPLICABLE)",
      "If this transaction is a \"home solicitation sale\" under Illinois law (for example, if you sign this agreement or authorize payment at your residence during an in-person solicitation), you may cancel until midnight of the third business day after the date of this transaction.",
      "Cancellation is effective upon mailing the Notice of Cancellation (postmark date) or upon delivery by another permitted method. If you timely cancel, we will return payments as required by law, including (where applicable) within 10 business days after receipt of your cancellation notice.",
      "Where applicable, we will provide the Notice of Cancellation in the form and manner required by Illinois law."
    ]
  },
  {
    "slug": "privacy",
    "path": "/privacy",
    "title": "Privacy Policy",
    "description": "SHYNLI LLC Privacy Policy explaining how client, booking, communication, payment, service, and website information is collected and used.",
    "sourceUrl": "https://shynlicleaningservice.com/privacy-policy",
    "lines": [
      "PRIVACY POLICY",
      "SHYNLI LLC (Illinois)",
      "Last Updated: February 16, 2026",
      "Time Zone: America/Chicago (Central Time)",
      "This Privacy Policy explains how SHYNLI LLC (\"Company,\" \"we,\" \"us,\" \"our\") collects, uses, discloses, and protects information that identifies, relates to, describes, or could reasonably be linked to an individual or household (\"Personal Information\") when you use our website, request a quote, book or receive cleaning services, or communicate with us (calls, SMS/text messages, email) (collectively, the \"Services\").",
      "This Privacy Policy applies to residential clients, business clients, and representatives/contacts acting on behalf of a business client.",
      "1) Relationship to Terms of Service",
      "Our Terms of Service (\"Terms\") govern the Services and contractual matters (scope, payments, cancellations, and dispute procedures). This Privacy Policy governs our Personal Information practices. If there is a conflict regarding privacy, this Privacy Policy will control to the extent permitted by law.",
      "2) Personal Information We Collect",
      "A. Information you provide directly",
      "- Contact details: name, email address, phone number (if provided), billing address (if applicable).",
      "- Service details: service address, property type, rooms/bathrooms, condition/soil level, special requests, scheduling details, parking/building requirements.",
      "- Access information: lockbox instructions, door codes, smart-lock credentials, key handoff details, entry notes, and related access constraints you provide to enable service delivery.",
      "- Business information (if applicable): company name, job title, and business contact details of authorized representatives.",
      "- Payment-related information: we may receive payment confirmation, limited transaction details (e.g., transaction ID, status), and other limited payment information from our payment processors. We do not intentionally collect or store full card numbers; payments are processed by third-party payment providers.",
      "- Communications: content of messages you send us via email, SMS/text, web forms, or phone.",
      "B. Information collected automatically (website and devices)",
      "- Device and usage data: IP address, browser type, device identifiers, pages visited, time spent, clicks, and referring URLs.",
      "- Cookies and similar technologies: used to operate the website, remember preferences, analyze traffic, and (if enabled) measure advertising performance. See Section 7.",
      "C. Information collected during service delivery",
      "- Quality control photos (\"QC photos\"): before/after photos as described in Section 9 and our Terms.",
      "- Call recordings (if used): where permitted by law and after appropriate notice/consent as described in Section 6.",
      "- Service notes: internal notes about service completion, access issues, and scope-related observations relevant to performance and quality.",
      "D. Information from third parties",
      "- Scheduling/CRM and communications tools: appointment metadata, delivery status, opt-in/opt-out status, timestamps, and message routing information.",
      "- Payment processors: payment confirmation and limited transaction details.",
      "- Review platforms: information you submit publicly (e.g., Google, Yelp), and related engagement metadata.",
      "3) What We Do Not Intentionally Collect",
      "- Children's data: our Services are not directed to children under 13, and we do not knowingly collect Personal Information from children under 13.",
      "- Sensitive identifiers: we do not request Social Security numbers, driver's license numbers, or biometric identifiers as part of normal operations.",
      "- Undisclosed audio recording on premises: we do not consent to undisclosed audio recording of private conversations on client premises (see Terms).",
      "4) How We Use Personal Information",
      "We use Personal Information to:",
      "- Provide, schedule, and perform cleaning services, including access coordination and service logistics.",
      "- Communicate about your booking (confirmations, reminders, access questions, schedule changes, invoices, service updates).",
      "- Process payments, administer deposits/prepayments (if applicable), and prevent fraud.",
      "- Provide customer support and respond to requests.",
      "- Improve our Services and website performance.",
      "- Maintain quality standards, including internal quality control, training, and dispute handling (including QC photos where applicable).",
      "- Maintain records of SMS/marketing consent and opt-out requests as needed to honor preferences and comply with applicable communications laws.",
      "- Comply with legal obligations, enforce our Terms, and protect rights, property, and safety.",
      "5) Legal Bases (Where Applicable)",
      "Where required by applicable law, we rely on one or more of the following:",
      "- Performance of a contract (providing requested Services).",
      "- Legitimate interests (security, quality improvement, fraud prevention, dispute resolution).",
      "- Consent (where required for marketing communications, certain cookies, and call recording).",
      "- Legal obligation (tax, accounting, consumer protection, or other compliance requirements).",
      "6) Communications: SMS/Text, Calls, Email",
      "A. Transactional/service communications",
      "We send service-related messages as reasonably necessary to provide and manage your booking (e.g., confirmations, access questions, schedule changes, invoices).",
      "B. Marketing communications",
      "- Email: we may send marketing emails if you opted in or where permitted by law.",
      "- SMS/Text and Calls: we will not send marketing texts/calls without prior express consent where required.",
      "- Consent not required to purchase: your consent to marketing messages is not a condition of purchasing Services.",
      "C. Opt-out",
      "- Marketing SMS: reply STOP to opt out; for help reply HELP (where applicable). Message frequency varies. Standard message/data rates may apply.",
      "- Marketing email: use the unsubscribe link in the email or contact us at info@shynli.com.",
      "You may still receive transactional/service messages necessary to complete Services you requested.",
      "D. Call recording (if applicable)",
      "Where permitted by law, we may record inbound/outbound calls for quality assurance, training, and dispute resolution after providing notice (including automated notice at call start where used). By continuing the call after the recording notice, you consent to recording to the extent permitted by applicable law. If you prefer not to be recorded, you may request to communicate via email/SMS instead.",
      "7) Cookies, Analytics, and Advertising",
      "We use cookies and similar technologies (such as pixels, tags, SDKs) for:",
      "Essential site functionality. To operate the website, maintain security, prevent fraud, and enable core features.",
      "Analytics. We use analytics tools (including Google Analytics) to understand how visitors use our website (e.g., pages viewed, time on site, general location inferred from IP, device/browser information) so we can improve content and Services.",
      "Advertising and measurement. We may use advertising and measurement tools (including Meta Pixel and Google Ads technologies) to measure the effectiveness of ads, build audiences for advertising (e.g., people who visited certain pages), and deliver ads on third-party platforms that may be more relevant to you.",
      "Your choices (Cookie Banner / Cookie Settings). You can manage non-essential cookies via our Cookie Banner / Cookie Settings on the website. You can also control cookies through your browser settings. Disabling certain cookies may affect website functionality.",
      "Global Privacy Control (GPC) / Do Not Track (DNT). Some browsers transmit Global Privacy Control (GPC) or \"Do Not Track\" signals. Where required by applicable law, we treat GPC as a valid request to opt out of certain uses that may be considered \"sharing\" for targeted advertising (e.g., certain third-party advertising cookies/pixels). Our response to DNT may vary.",
      "8) How We Share Personal Information",
      "We do not sell Personal Information. We may allow certain third-party advertising/analytics partners to collect information via cookies/pixels on our website, which may be considered \"sharing\" for targeted advertising under some U.S. state privacy laws. You can opt out of non-essential cookies and similar technologies through our Cookie Settings (Section 7) and, where applicable, via GPC.",
      "A. Service providers (processors)",
      "We share Personal Information with vendors who help us operate our business, such as:",
      "- Payment processing: Stripe (and other payment handling as applicable).",
      "- Scheduling/CRM: GoHighLevel.",
      "- SMS/communications: Twilio.",
      "- Website hosting, analytics providers, email service providers (if used), and other operational vendors.",
      "These providers may access Personal Information only to perform services for us and are expected to protect it.",
      "B. Legal, safety, and dispute-related disclosures",
      "We may disclose information if reasonably necessary to:",
      "- Comply with law, court orders, subpoenas, or lawful requests.",
      "- Protect the rights, property, and safety of the Company, clients, our personnel, or others.",
      "- Investigate, defend, or resolve a claim or dispute (including sharing relevant information and QC photos with insurers, legal counsel, or dispute-resolution providers).",
      "C. Business transfers",
      "If we are involved in a merger, acquisition, financing, reorganization, or sale of assets, Personal Information may be transferred as part of that transaction, subject to appropriate confidentiality protections.",
      "9) Photos for Quality Control (QC)",
      "Purpose. We may take before/after photos solely for internal quality control, training, and dispute review. We use reasonable efforts to avoid capturing people, personal documents, or sensitive items.",
      "No marketing use without consent. We do not use QC photos for marketing, public posting, or advertising without your separate express consent.",
      "Permitted disclosure. We may share QC photos with our insurers, legal counsel, and/or dispute-resolution providers as reasonably necessary to investigate, defend, or resolve a claim or dispute.",
      "Retention. QC photos are typically retained for up to 90 days, unless longer retention is reasonably needed for a dispute or to comply with law.",
      "Opt-out. You may opt out by notifying us before service begins (phone/SMS/email/message). If you opt out, we may request an alternative acceptance/verification process (e.g., walk-through, checklist sign-off), and the absence of photos may limit our ability to investigate certain disputes.",
      "10) Data Retention",
      "We retain Personal Information only as long as reasonably necessary for:",
      "- Providing Services and managing appointments,",
      "- Recordkeeping (tax/accounting),",
      "- Dispute resolution and enforcement of agreements,",
      "- Legal compliance.",
      "Retention periods vary depending on the type of data and applicable requirements. We may retain transaction and invoice records for accounting and legal compliance, and retain consent/opt-out logs as needed to honor preferences and comply with communications laws.",
      "11) Data Security",
      "We implement reasonable administrative, security, and physical safeguards designed to protect Personal Information. However, no method of transmission or storage is 100% secure.",
      "You are responsible for providing accurate access information (e.g., codes/lockbox instructions) and updating us if details change.",
      "Security incident notice (Illinois). If we become aware of a security incident involving Personal Information, we will take reasonable steps to investigate and mitigate the incident and, where required by applicable law (including Illinois law), notify affected individuals and/or regulators.",
      "12) Your Privacy Rights and Choices (U.S. State Notices)",
      "Depending on where you live and applicable law, you may have rights such as:",
      "- Access: request access to certain Personal Information we hold about you.",
      "- Correction: request correction of inaccurate Personal Information.",
      "- Deletion: request deletion of certain Personal Information (subject to legal and contractual exceptions).",
      "- Opt out of targeted advertising / \"sharing\": you may opt out of certain cookie-based data uses that may be considered targeted advertising or \"sharing\" under some state laws by using our Cookie Settings and, where applicable, enabling Global Privacy Control (GPC) in your browser.",
      "- Opt out of marketing: opt out of marketing communications (Section 6).",
      "How to submit requests. To exercise rights, contact us at info@shynli.com. We may need to verify your identity before fulfilling requests. If you use an authorized agent where permitted by law, we may require proof of authorization.",
      "Appeals (where required). If we deny your request, you may appeal by replying to our response email and stating you wish to appeal. We will review and respond as required by applicable law.",
      "13) Third-Party Links",
      "Our website may include links to third-party websites or services (including payment pages and review platforms). We are not responsible for their privacy practices. Please review their privacy policies.",
      "14) Changes to This Privacy Policy",
      "We may update this Privacy Policy from time to time. Updates apply as of the \"Last Updated\" date above. For material changes, we may provide additional notice as required by law.",
      "15) Contact Us",
      "SHYNLI LLC",
      "Attn: Privacy",
      "Email: info@shynli.com",
      "Phone: +1(630)812-7077",
      "Mailing Address: P.O. Box 2492",
      "Naperville IL 60566",
      "Website: https://shynlicleaningservice.com"
    ]
  },
  {
    "slug": "cancellation",
    "path": "/cancellation",
    "title": "Cancellation Policy",
    "description": "SHYNLI LLC Cancellation Policy for cancellations, reschedules, no-access, late arrival, deposits, refunds, and rebooking.",
    "sourceUrl": "https://shynlicleaningservice.com/cancellation-policy",
    "lines": [
      "CANCELLATION POLICY",
      "Last Updated: February 13, 2026",
      "Time Zone: America/Chicago (Central Time)",
      "This Cancellation Policy applies to all bookings with SHYNLI LLC (\"Company,\" \"we,\" \"us\"). By booking services, you agree to this policy and our Terms of Service. This policy is a summary; the Terms of Service control in case of any inconsistency.",
      "1) How to Cancel or Reschedule",
      "You may cancel or reschedule by:",
      "- replying to our confirmation/reminder SMS/text, or",
      "- emailing info@shynli.com, or",
      "- calling/texting +1(630)812-7077.",
      "Requests are effective when received by us; processing may be delayed outside normal operating hours. All timing is based on Central Time (America/Chicago).",
      "2) Cancellation / Reschedule Fees",
      "If you cancel or reschedule:",
      "- More than 48 hours before the appointment: $0",
      "- 24-48 hours before: $50 flat fee",
      "- 12-24 hours before: 50% of the booked price",
      "- Less than 12 hours before, or same-day cancellation or reschedule: 100% of the booked price",
      "These fees are liquidated damages intended to cover reserved team time and dispatch/processing costs, not a penalty, and will not exceed the booked price. Dispatch/processing costs (if incurred) are non-refundable to the extent permitted by law.",
      "3) No-Show / No-Access (100% Fee)",
      "A booking may be treated as a no-show and charged 100% of the booked price if our team arrives but:",
      "- we cannot enter (locked door, incorrect/failed code, missing key/lockbox access),",
      "- building/security denies entry,",
      "- the property is unavailable (including because guests have not checked out) or a vacant window is not provided (including short-term rentals), or",
      "- you are unreachable and cannot provide access.",
      "15-minute rule: If entry cannot be obtained within 15 minutes of arrival due to access issues, the appointment may be treated as a no-show.",
      "Optional waiting: If you request the team to wait beyond 15 minutes (and we are able to stay), waiting time may be billed at $45/hour, prorated.",
      "4) Rebooking Reduction (Mitigation)",
      "If we successfully rebook your cancelled/rescheduled time slot, we will reduce your cancellation fee by the amount of labor revenue recovered from the replacement booking (excluding non-refundable dispatch/processing costs already incurred), up to the fee charged.",
      "5) Payments, Deposits, and Refunds",
      "- We may require a valid payment method to reserve your time slot and may charge applicable cancellation/no-show fees if triggered.",
      "- If a prepayment/deposit was collected and a refund is due, refunds are issued to the original payment method when feasible, subject to bank/processor timelines.",
      "6) Late Arrivals by the Company",
      "Appointment times are estimated service windows. Delays may occur due to traffic, weather, building access constraints, or conditions at prior jobs.",
      "If we arrive more than 60 minutes late for reasons within our reasonable control and cannot complete the booked scope, we will reschedule at no charge or issue a proportional credit for the unperformed portion (Company's choice), unless a different remedy is required by law. This does not apply to delays outside our reasonable control (for example, severe weather, road closures/accidents, emergencies, or building access restrictions).",
      "7) Safety/Unsuitable Conditions",
      "If service is refused or terminated due to unsafe conditions, prohibited conditions, or conduct issues (see our Terms), we may retain amounts reasonably related to reserved labor time, dispatch/travel, and costs incurred, and may invoice for work performed, subject to refunds required by law.",
      "8) Changes to This Policy",
      "We may update this policy from time to time. Updates apply as of the \"Last Updated\" date above and generally apply to bookings made after the update date.",
      "Questions: info@shynli.com | +1(630)812-7077"
    ]
  }
] as const
